# Generated by Django 5.0.1 on 2024-02-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FreeAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipus", models.CharField(max_length=100)),
                ("honap", models.CharField(max_length=100)),
                ("nap", models.IntegerField()),
                ("idopont", models.TimeField()),
            ],
        ),
    ]
