# Generated by Django 5.0.1 on 2024-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_freeappointment_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="free",
            field=models.BooleanField(default=True),
        ),
    ]
