# Generated by Django 5.0.1 on 2024-02-06 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_appointment_free"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="tipus",
        ),
    ]
